package main

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"late/internal/assets"
	"late/internal/client"
	"late/internal/common"
	appconfig "late/internal/config"
	"late/internal/debug"
	"late/internal/executor"
	"late/internal/mcp"
	"late/internal/orchestrator"
	"late/internal/pathutil"
	"late/internal/session"
	"late/internal/tool"
)

type sessionResult struct {
	sess            *session.Session
	rootAgent       *orchestrator.BaseOrchestrator
	initialMsg      string
	debugLog        *debug.Logger
	scanCache       *executor.ToolResultCache
	reportWrittenCh chan string
}

type scanBuildConfig struct {
	defaultRetestPath string
	pickedTarget      string
	pickedLocalPath   string
	pickedOutputDir   string
	pickedRetestPath  string
	defaultOutputDir  string
	cwd               string
	containerName     string
	workDir           string
	networkName       string
	composeProject    string
	historyPath       string
	sastCfgDir        string
	gemmaThinking     bool
	reservedHostPorts []int
	enabledTools      map[string]bool
	mainClient        *client.Client
	mcpClient         *mcp.Client
}

type scanBuildDeps struct {
	readPromptFile          func(name string) ([]byte, error)
	readFile                func(name string) ([]byte, error)
	mkdirAll                func(path string, perm os.FileMode) error
	loadConfigFromDir       func(path string) (*appconfig.Config, error)
	newProContextClient     func() (*tool.ProContextClient, error)
	fetchAndIndexSemgrepRef func(context.Context, *tool.ContextIndex, string) error
}

func defaultScanBuildDeps() scanBuildDeps {
	return scanBuildDeps{
		readPromptFile:          assets.PromptsFS.ReadFile,
		readFile:                os.ReadFile,
		mkdirAll:                os.MkdirAll,
		loadConfigFromDir:       appconfig.LoadConfigFromDir,
		newProContextClient:     tool.NewProContextClient,
		fetchAndIndexSemgrepRef: fetchAndIndexSemgrepSkills,
	}
}

func buildScanSession(cfg scanBuildConfig) (sessionResult, error) {
	return buildScanSessionWithDeps(cfg, defaultScanBuildDeps())
}

func buildScanSessionWithDeps(cfg scanBuildConfig, deps scanBuildDeps) (sessionResult, error) {
	activeRetestPath := cfg.defaultRetestPath
	if cfg.pickedRetestPath != "" {
		activeRetestPath = cfg.pickedRetestPath
	}
	if activeRetestPath != "" {
		abs, err := filepath.Abs(activeRetestPath)
		if err != nil {
			return sessionResult{}, fmt.Errorf("error resolving retest path: %w", err)
		}
		if _, err := os.Stat(abs); err != nil {
			return sessionResult{}, fmt.Errorf("retest report %q does not exist", abs)
		}
		activeRetestPath = abs
	}

	pickedOutputDir := cfg.pickedOutputDir
	if pickedOutputDir == "" {
		pickedOutputDir = cfg.defaultOutputDir
	}

	repoName := "repo"
	if cfg.pickedLocalPath != "" {
		if base := filepath.Base(cfg.pickedLocalPath); base != "" && base != "." {
			repoName = base
		}
	} else if cfg.pickedTarget != "" {
		if parts := strings.Split(strings.TrimRight(cfg.pickedTarget, "/"), "/"); len(parts) > 0 {
			if last := parts[len(parts)-1]; last != "" {
				repoName = last
			}
		}
	}

	promptFile := "prompts/instruction-sast.md"
	if activeRetestPath != "" {
		promptFile = "prompts/instruction-sast-retest.md"
	}
	content, err := deps.readPromptFile(promptFile)
	if err != nil {
		return sessionResult{}, fmt.Errorf("error loading SAST system prompt: %w", err)
	}
	systemPrompt := string(content)
	pickedTarget := cfg.pickedTarget

	if activeRetestPath != "" {
		reportBytes, readErr := deps.readFile(activeRetestPath)
		if readErr != nil {
			return sessionResult{}, fmt.Errorf("error reading retest report: %w", readErr)
		}
		parsedTarget, parsedRepo := parseReportHeader(string(reportBytes))
		if parsedTarget == "" {
			return sessionResult{}, fmt.Errorf("could not find a 'Target:' line in the first 20 lines of %s\n\nMake sure the file is a SAST report generated by late-sast", activeRetestPath)
		}
		pickedTarget = parsedTarget
		if parsedRepo != "" {
			repoName = parsedRepo
		}
	}

	if err := deps.mkdirAll(pickedOutputDir, 0755); err != nil {
		return sessionResult{}, fmt.Errorf("error creating output directory: %w", err)
	}

	systemPrompt = common.ReplacePlaceholders(systemPrompt, map[string]string{
		"${{CWD}}":             cfg.cwd,
		"${{CONTAINER_NAME}}":  cfg.containerName,
		"${{WORKDIR}}":         cfg.workDir,
		"${{REPO_NAME}}":       repoName,
		"${{OUTPUT_DIR}}":      pickedOutputDir,
		"${{NETWORK_NAME}}":    cfg.networkName,
		"${{COMPOSE_PROJECT}}": cfg.composeProject,
		"${{VERSION}}":         common.Version,
	})

	if cfg.gemmaThinking {
		systemPrompt = "<|think|>" + systemPrompt
	}

	var initialMessage string
	switch {
	case activeRetestPath != "":
		initialMessage = fmt.Sprintf("Retest the confirmed and likely findings from the previous SAST report.\nPrevious report: %s\nTarget: %s", activeRetestPath, pickedTarget)
	case cfg.pickedLocalPath != "":
		initialMessage = fmt.Sprintf("Perform a complete security audit of the local repository at: %s", cfg.pickedLocalPath)
	case pickedTarget != "":
		initialMessage = fmt.Sprintf("Perform a complete security audit of: %s", pickedTarget)
	}

	reportLabel := fmt.Sprintf("sast_report_%s.md", repoName)
	if activeRetestPath != "" {
		reportLabel = fmt.Sprintf("sast_retest_%s.md", repoName)
	}
	fmt.Println("Starting late-sast...")
	fmt.Printf("[late-sast] Report will be written to: %s/%s\n", pickedOutputDir, reportLabel)

	mainClient := cfg.mainClient
	if mainClient == nil {
		mainClient = client.NewClient(client.Config{})
	}
	sess := session.New(mainClient, cfg.historyPath, []client.ChatMessage{}, systemPrompt, true)

	var debugLog *debug.Logger
	if latestCfg, err := deps.loadConfigFromDir(cfg.sastCfgDir); err == nil && latestCfg != nil && latestCfg.DebugLogging {
		debugLog = debug.New(pickedOutputDir)
		sess.SetDebugLogger(debugLog)
		if debugLog.Enabled() {
			fmt.Printf("[late-sast] Debug logging enabled → %s\n", debugLog.FilePath())
		}
	}

	reportWrittenCh := make(chan string, 4)
	registerScanTools(sess, registerScanToolsConfig{
		reservedHostPorts: cfg.reservedHostPorts,
		reportWrittenCh:   reportWrittenCh,
		enabledTools:      cfg.enabledTools,
		mcpClient:         cfg.mcpClient,
	}, deps)

	rootAgent := orchestrator.NewBaseOrchestrator("main", sess, nil, 0)
	rootAgent.SetCoordinator(executor.GlobalGPU)
	scanCache := executor.NewToolResultCache()
	rootAgent.SetSharedCache(scanCache)
	orchestrator.GlobalBlackboard.ResetExploitState()

	return sessionResult{
		sess:            sess,
		rootAgent:       rootAgent,
		initialMsg:      initialMessage,
		debugLog:        debugLog,
		scanCache:       scanCache,
		reportWrittenCh: reportWrittenCh,
	}, nil
}

type registerScanToolsConfig struct {
	reservedHostPorts []int
	reportWrittenCh   chan string
	enabledTools      map[string]bool
	mcpClient         *mcp.Client
}

func registerScanTools(sess *session.Session, cfg registerScanToolsConfig, deps scanBuildDeps) {
	sess.Registry.Register(&tool.ShellTool{
		Analyzer:     &tool.SASTBashAnalyzer{},
		SkipSafePath: true,
		Timeout:      5 * time.Minute,
	})
	sess.Registry.Register(tool.NewReadFileTool())
	sess.Registry.Register(tool.WriteFileTool{})
	sess.Registry.Register(tool.SetupContainerTool{})
	sess.Registry.Register(tool.LaunchDockerTool{ReservedHostPorts: cfg.reservedHostPorts})
	sess.Registry.Register(tool.WaitForTargetReadyTool{})
	sess.Registry.Register(tool.BootstrapScanToolchainTool{})
	sess.Registry.Register(tool.WriteSASTReportTool{
		OnWritten: func(path string) {
			select {
			case cfg.reportWrittenCh <- path:
			default:
			}
		},
	})
	sess.Registry.Register(tool.VulVendorProductCVETool{})
	sess.Registry.Register(tool.VulCVESearchTool{})
	sess.Registry.Register(tool.VulVendorProductsTool{})
	sess.Registry.Register(tool.VulLastCVEsTool{})
	sess.Registry.Register(tool.PatchComposeNetworkTool{})

	if docsClient, docsErr := deps.newProContextClient(); docsErr != nil {
		fmt.Fprintf(os.Stderr, "Warning: ProContext registry unavailable (%v) — docs_resolve/read/search disabled\n", docsErr)
	} else {
		sess.Registry.Register(tool.DocsResolveTool{Client: docsClient})
		sess.Registry.Register(tool.DocsReadTool{Client: docsClient})
		sess.Registry.Register(tool.DocsSearchTool{Client: docsClient})
	}

	ctxIdx := tool.NewContextIndex()
	indexSASTReferences(ctxIdx, "/tmp/sast-skill")
	semgrepCacheDir := func() string {
		if d, err := pathutil.LateSASTCacheDir(); err == nil {
			return filepath.Join(d, "semgrep-skills")
		}
		return "/tmp/semgrep-skills"
	}()
	if err := deps.fetchAndIndexSemgrepRef(context.Background(), ctxIdx, semgrepCacheDir); err != nil {
		fmt.Fprintf(os.Stderr, "Warning: semgrep code-security skills unavailable (%v) — skipping\n", err)
	}
	sess.Registry.Register(tool.CtxIndexTool{Index: ctxIdx})
	sess.Registry.Register(tool.CtxSearchTool{Index: ctxIdx})
	sess.Registry.Register(tool.CtxFetchAndIndexTool{Index: ctxIdx})
	sess.Registry.Register(tool.CtxIndexFileTool{Index: ctxIdx})

	if cfg.mcpClient == nil {
		return
	}
	for _, mcpTool := range cfg.mcpClient.GetTools() {
		if enabled, exists := cfg.enabledTools[mcpTool.Name()]; exists && !enabled {
			continue
		}
		sess.Registry.Register(mcpTool)
	}
}
